name: ci
on:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:

  ############################ tests ############################

  lint-helm:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@4.1
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: earthly +lint

  ############################ helm ############################

  helm-publish:
    runs-on: [self-hosted]
    needs: [lint-helm]
    steps:
    - uses: eniblock/build/actions/setup@4.1
      id: setup
      with:
        helmdir: cockroachdb
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build/Publish the helm charts
      run: |
        earthly \
          --secret registry_password=${{ github.token }} \
          +publish \
          --tag=${{ steps.setup.outputs.tag }}
    - name: Generate job summary
      run: |
        cat <<"EOF" >> $GITHUB_STEP_SUMMARY
        ## Helm package
        Helm package was generated with tag `${{ env.TAG }}`

        Use it directly with

        ~~~bash
        helm install cockroachdb oci://ghcr.io/eniblock/cockroachdb --version ${{ env.TAG }}
        ~~~

        or as a helm dependency in your `Chart.yaml`:

        ~~~yaml
        dependencies:
          - name: cockroachdb
            version: "${{ env.TAG }}"
            repository: "oci://ghcr.io/eniblock"
        ~~~
        EOF
